# Macro file for the initialization of example B1
# in interactive session
#
# Set some default verbose
#/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
/gps/particle gamma
/gps/ene/type Lin
/gps/ene/min 0.2 MeV
/gps/ene/max 5. MeV
/gps/ene/gradient 0
/gps/ene/intercept 1
#/gps/energy 1 MeV
/gps/ang/type iso
#
#/run/beamOn 500
